//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.05 at 04:42:29 PM MSK 
//


package ru.gov.zakupki.oos.pprf615types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Тип: Отказ от заключения контракта
 * 
 * <p>Java class for refusalFact complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="refusalFact">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="foundation" type="{http://zakupki.gov.ru/oos/base/1}text2000Type"/>
 *         &lt;element name="voucherEntry" type="{http://zakupki.gov.ru/oos/base/1}text2000Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "refusalFact", propOrder = {
    "foundation",
    "voucherEntry"
})
public class RefusalFact {

    @XmlElement(required = true)
    protected String foundation;
    @XmlElement(required = true)
    protected String voucherEntry;

    /**
     * Gets the value of the foundation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFoundation() {
        return foundation;
    }

    /**
     * Sets the value of the foundation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFoundation(String value) {
        this.foundation = value;
    }

    /**
     * Gets the value of the voucherEntry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoucherEntry() {
        return voucherEntry;
    }

    /**
     * Sets the value of the voucherEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoucherEntry(String value) {
        this.voucherEntry = value;
    }

}
